### ISSUE TITLE
Missing Relationships.py script

### ISSUE THREAD

**Issue by pls256** [usgs/GeMS_Tools#13]
This script "Relationships.py" is missing from distribution. It is referenced in the toolbox but missing from both the documentation and the scripts folder.

**Comment by rhaugerud** [comment]
Oops.  Fixed this. There is now a script which seems to function fairly well. 
I don't use relationship classes much, so am not sure how useful this script will be. Let me know if you see things that could be improved.

**Comment by rhaugerud** [comment]
Oops. Fixed this. There is now a script which seems to function fairly well.
I don't use relationship classes much, so am not sure how useful this script will be. Let me know if you see things that could be improved.
You'll need the newest GeMS_ToolsArc10x.tbx file. Best to download the whole repo.

**Comment by pls256** [comment]
Thank you. I will test. I had written my own while waiting but always interested in seeing alternative code.
