### ISSUE TITLE
Increase the character length in notes fields

### ISSUE THREAD

**Issue by Lbookman** [usgs/GeMS_Tools#14]
The character length of the notes fields is 254. Is it possible to increase the character length? @rhaugerud

**Comment by rhaugerud** [comment]
Laura-

The draft standard doesn't prescribe the length of the Notes field.  It can
be whatever you would like.

Here are two ways to change the length of the Notes field:

1) Make a new database. Load the feature class you want to change into an
ArcMap document. Open the attribute table. Delete the Notes field. Add a
new Notes field, specify that its type is text, and set the length to
whatever you desire.

2) Open file GeMS_Definition.py (in the Scripts directory) for editing.
Find, in or following the lines

startDict = {
# required tables and feature classes
               'MapUnitPolys':
 [['MapUnit','String','NoNulls',mapUnitLength],

 ['IdentityConfidence','String','NoNulls',IDLength],

 ['Label','String','NullsOK',IDLength],

 ['Symbol','String','NullsOK',defaultLength],

the line defining the Notes field you want to change. e.g.



 ['Notes','String','NullsOK',defaultLength]],

Change defaultLength to the length you would like, e.g.



 ['Notes','String','NullsOK',500]],


Save the edited file.

Make a new database.

Hope this helps.

Ralph

----
Ralph Haugerud
Geologist, US Geological Survey
c/o Earth & Space Sciences
University of Washington
Seattle, WA 98195
  rhaugerud@usgs.gov
  haugerud@u.washington.edu
